print("What is your name?")
name = input()
print("What is your job's name?")
job_name = input()
print("An adjective for the cohort")
adj1 = input()
print("A second adjective for the teacher")
adj2 = input()
print("Mention a food for lunch")
food1 = input()
print("Mention another food for lunch")
food2 = input()
print("Mention a feeling")
feeling = input()

print (name, "started their first Generation course today. They are training as a", job_name + ".", "They found their cohort to be very", adj1, "but their teacher was, at least", adj2 + ".", "For lunch they have", food1, "and", food2, "while reviewing their notes. They feel", feeling, "but are determined to complete the course.")